### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by phpwalter** [algorys/bootnote#6]
I'm not getting the icons in the NOTE block as shown in your DOCs page.

http://walters-way.com
![2017-11-20 01_12_12-start walters way](https://user-images.githubusercontent.com/116952/33006405-e0d4db82-cd8f-11e7-806a-608b25bf0ecf.png)

**Comment by algorys** [comment]
Which version of Dokuwiki and PHP please ?

Do you use a Boostrap theme ? Like says in documentation for this theme ?

Do you have something in your logs when using plugin ?

Check also your settings.

**Comment by thomasbesorna** [comment]
I'm not getting the icons too.
![image](https://user-images.githubusercontent.com/39151138/39861059-b1612fea-543f-11e8-899f-0f109f7c76b8.png)

DokuWiki: stable-2018-04-22a_Greebo
PHP: 7.2
Theme: dokuwiki (default after installation)
Default settings.

**Comment by thomasbesorna** [comment]
Page's Source Code:

<p>
  | <div class="w3-panel n-info-sign"><p><span class="glyphicon glyphicon-info-sign blackglyph" aria-hidden="true"></span><span class="n-title">Note:</span> Your note</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-globe"><p><span class="glyphicon glyphicon-globe blackglyph" aria-hidden="true"></span><span class="n-title">Link:</span> display a note with an globe sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-question-sign"><p><span class="glyphicon glyphicon-question-sign blackglyph" aria-hidden="true"></span><span class="n-title">Question:</span> display a note with question sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-education"><p><span class="glyphicon glyphicon-education blackglyph" aria-hidden="true"></span><span class="n-title">To Know:</span> Do you want to learn something ?</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-education"><p><span class="glyphicon glyphicon-education blackglyph" aria-hidden="true"></span><span class="n-title">To Know:</span> display note with an education sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-alert"><p><span class="glyphicon glyphicon-alert blackglyph" aria-hidden="true"></span><span class="n-title">Warning:</span> display a note with a warning sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-fire"><p><span class="glyphicon glyphicon-fire blackglyph" aria-hidden="true"></span><span class="n-title">Important:</span> display a note with a fire sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-fire"><p><span class="glyphicon glyphicon-fire blackglyph" aria-hidden="true"></span><span class="n-title">Important:</span> display a note with a fire sign</p></div>
  | </p>

**Comment by thomasbesorna** [comment]
Source code for above:
`
<p>
  | <div class="w3-panel n-info-sign"><p><span class="glyphicon glyphicon-info-sign blackglyph" aria-hidden="true"></span><span class="n-title">Note:</span> Your note</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-globe"><p><span class="glyphicon glyphicon-globe blackglyph" aria-hidden="true"></span><span class="n-title">Link:</span> display a note with an globe sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-question-sign"><p><span class="glyphicon glyphicon-question-sign blackglyph" aria-hidden="true"></span><span class="n-title">Question:</span> display a note with question sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-education"><p><span class="glyphicon glyphicon-education blackglyph" aria-hidden="true"></span><span class="n-title">To Know:</span> Do you want to learn something ?</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-education"><p><span class="glyphicon glyphicon-education blackglyph" aria-hidden="true"></span><span class="n-title">To Know:</span> display note with an education sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-alert"><p><span class="glyphicon glyphicon-alert blackglyph" aria-hidden="true"></span><span class="n-title">Warning:</span> display a note with a warning sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-fire"><p><span class="glyphicon glyphicon-fire blackglyph" aria-hidden="true"></span><span class="n-title">Important:</span> display a note with a fire sign</p></div>
  | </p>
  |  
  | <p>
  | <div class="w3-panel n-fire"><p><span class="glyphicon glyphicon-fire blackglyph" aria-hidden="true"></span><span class="n-title">Important:</span> display a note with a fire sign</p></div>
  | </p>
 

`

**Comment by thomasbesorna** [comment]
Source Code for above:
`<div class="w3-panel n-info-sign"><p><span class="glyphicon glyphicon-info-sign blackglyph" aria-hidden="true"></span><span class="n-title">Note:</span> Your note</p></div>`

**Comment by thomasbesorna** [comment]
But where you are creating the icons in your code ??
`    function _render_note($renderer, $glyph) {`
`        if ($this->getConf('bootnote.theme') == 'oldtheme') {`
`            $renderer->doc .= '<div style="clear: both;">'; // Global`
`            $renderer->doc .= '<div class="sign-container">';`
`            $renderer->doc .= '  <span class="sign">';`
`            $renderer->doc .= '    <span class="glyphicon glyphicon-'.$glyph.' s-'.$glyph.' glyph" aria-hidden="true"></span>';`
`            $renderer->doc .= '  </span>'; // /.sign`
`            $renderer->doc .= '</div>'; // /.sign-container`
`            $renderer->doc .= '<div class="note-container s-'.$glyph.'">';`
`            $renderer->doc .= '<div class="note">';`
`       } else {`
`            $renderer->doc .= '<div class="w3-panel n-'.$glyph.'"><p>';`
`            $renderer->doc .= '<span class="glyphicon glyphicon-'.$glyph.' blackglyph" aria-hidden="true"></span>';`
`            $renderer->doc .= '<span class="n-title">'.$this->getTitle($glyph).':</span>';`
`            if ($this->getConf('bootnote.position') == 'below') {`
`                $renderer->doc .= '</p>';`
`                $renderer->doc .= '<p>';`
`            } else {`
`                $renderer->doc .= ' '; // Need a space to separate title from text`
`            }`
`       }`
`    }`

**Comment by algorys** [comment]
@thomasbesorna this plugin have not yet been test on **Greebo** version.

Icons are created here: `$renderer->doc .= '<div class="note-container s-'.$glyph.'">';` by `$glyph` var.

I'll have a look ASAP.

**Comment by algorys** [comment]
@thomasbesorna if you don't have a boostrap theme, it's normal that the icons do not display, like says [here](https://github.com/algorys/bootnote#requirements).

These icons are related to boostrap and the plugin needs to display them :wink: so plugin works as expected.

**Comment by algorys** [comment]
@thomasbesorna , @phpwalter  so can I close this issue ?
